---
DATA:
  dir: "/Volumes/GoogleDrive-108722195023672559969/Shared drives/QuantitativeBiology/Datasets"
  min_count: 300

ML:
  model: "rf"
  dataset_y: "drug_response"
  params_grid:
    criterion: ["mse"]
    n_estimators: [600] # [400, 600, 800, 1000]
    min_samples_split: [5] # [2, 5]
    min_samples_leaf: [2] # [1, 2]
    max_features: ["sqrt"]
    n_jobs: [4]
  cv:
    n_splits: 5

OUTPUT:
  file: "data/ML_phenotype_prediction.csv"